name: Deploy sam app

on:
  push:
    branches:
      - main
      - '*'
      - '*/'
      - '**'

defaults:
  run:
    working-directory: ./kjell

jobs:
  deploy-build-sam:
    runs-on: ubuntu-latest
    env:
      S3_ARTIFACT_BUCKET_NAME: pgr301-sam-bucket    # Using this as default bucket for exam
      SAM_APP: sam-app-ppe-detection-sensur         # Name of your sam app
      MY_BUCKET_NAME: "kandidatnr-2038s"             # Bucket used here is the one used for exam with kandidatnr

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}           # These are taken from Github secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   # These are taken from Github secrets
          aws-region: eu-west-1

      - name: Sam build and deploy on main branch
        if: github.ref == 'refs/heads/main'
        # set variable to get name instead, nicer.
        run: |
          sam build --use-container
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name $SAM_APP --s3-bucket $S3_ARTIFACT_BUCKET_NAME --capabilities CAPABILITY_IAM --region eu-west-1 --parameter-overrides MyBucketName=$MY_BUCKET_NAME

      - name: Sam build only if not on main branch
        if: github.ref != 'refs/heads/main'
        run: sam build --use-container